# for training all models
missing_value: ~
split_ratio: [0.8,0.1,0.1]
train:
  learning_rate: 0.001
  weight_decay: 0
  learner: adam
  scheduler: ~
  epochs: 100
  batch_size: 128
  shuffle: True
  save_path: ~
  num_workers: 12
  devices: 1
  seed: 20
  accelerator: gpu

eval:
  test_metrics: [rmse, mae, mape]
  val_metrics: [mae]
  early_stop_mode: min
  early_stop_patience: 10
  batch_size: 512
  num_workers: 12
