model:
  hist_steps: 1h
  pred_steps: 1h
  max_diffusion_step: 2
  hidden_dim: 64
  num_layers: 2
  use_gc_for_ru: true
  use_scheduled_sampling: true
  cl_decay_steps: 1000

data:
  mode: epsilon
  epsilon: 0.1
  sigma2: std
  sysmetrize_aggregation: ~
