model:
  hist_steps: 1h
  pred_steps: 1h
  drop_ratio: 0
  num_layers: 2
  gcn_order: 2
  tcn_kernel: 2
  tcn_input_dim: 32
  tcn_output_dim: 32
  block_output_dim: 256
  mlp_hidden_dim: 512
  ada_graph_emb_dim: 10

data:
  mode: epsilon
  epsilon: 0.1
  sigma2: std
  symmetrize_aggregation: ~

